### ISSUE TITLE
AndroidStudio 3.4能生成模版吗？

### ISSUE THREAD

**Issue by bannerkun** [qingmei2/MVVM-Rhine-Template#3]

**Comment by bannerkun** [comment]
报错了
<img width="2480" alt="屏幕快照 2019-04-28 下午2 01 12" src="https://user-images.githubusercontent.com/49234780/56860212-295a5780-69be-11e9-9638-59bbf0778906.png">

**Comment by qingmei2** [comment]
@bannerkun 

抱歉，最近对框架进行了大幅的调整，模版可能会晚几天，最迟5月3日之前更新。

不过你这个好像和框架无关，之前3.3是可以生成的，3.4我还没有尝试，等这两天我更新之后再回复你把

**Comment by qingmei2** [comment]
@bannerkun 

模版更新了，我这边3.4进行了测试，是可以的成功生成对应文件的，你试试呢

**Comment by bannerkun** [comment]
@bannerkun 谢谢
